AWSTemplateFormatVersion: 2010-09-09
Description: |
  This is my Cfn template for EC2 with Security Group

Parameters:
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64"

Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      KeyName: firstkey # Use your own key pair without ".pem"
      SecurityGroups:
        - !Ref WebServerInstanceSG
      Tags:
        - Key: Name
          Value: !Sub Derya ${AWS::StackName}
      UserData:
        Fn::Base64: |
          #! /bin/bash
          yum update -y 
          yum install httpd -y
          FOLDER="https://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@raw.githubusercontent.com/Derya-E/kittens-carousel-static-website-ec2/main/static-web"
          cd /var/www/html
          wget $FOLDER/index.html
          wget $FOLDER/cat0.jpg
          wget $FOLDER/cat1.jpg
          wget $FOLDER/cat2.jpg
          systemctl start httpd
          systemctl enable httpd
  WebServerInstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows SSH and HTTP for web server # Required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  WebSiteURL:
    Description: This output gives the URL of EC2
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt WebServerInstance.PublicDnsName
